#!/bin/sh

# We do not use symlinks anymore
# if [ $(uname -s) == 'MINGW32_NT-5.1' ]; then
  # rktools="$PROGRAMFILES/Windows Resource Kits/Tools"

  # if [ ! -d "$rktools" ]; then
    # echo "Installing Windows Server 2003 Resource Kit Tools ..."

    # cd $TMP > /dev/null

    # if [ ! -f "rktools.exe" ]; then
      # curl -O "http://download.microsoft.com/download/8/e/c/8ec3a7d8-05b4-440a-a71e-ca3ee25fe057/rktools.exe"
    # fi

    # rm -rf rktools
    # cmd //C "rktools.exe /T:""%TEMP%\\rktools"" /C"
    # cmd //C "msiexec /qn /i rktools\\rktools.msi"

    # cd - > /dev/null

    # if [ -d "$rktools" ]; then
      # echo "Windows Server 2003 Resource Kit Tools installed. Please restart GIT Bash and call ./init again."
    # else
      # echo "Installation failed. Please visit http://vvvv.org/documentation/vvvv-sdk and install it manually."
    # fi
    # exit 0
  # fi
# fi

# Because of http://msbuildtasks.tigris.org/issues/show_bug.cgi?id=148 we switched to cmd line call to 7-Zip.
# No need to install MSBuildCommunityTasks for now.
# if [ ! -d "$PROGRAMFILES/MSBuild/MSBuildCommunityTasks" ]; then
  # echo "Installing MSBuild Community Tasks ..."

  # cd $TMP > /dev/null
  
  # curl -O "http://msbuildtasks.tigris.org/MSBuild.Community.Tasks.Nightly.msi"
  
  # cmd //C "msiexec /qf /i MSBuild.Community.Tasks.Nightly.msi"
  
  # cd - > /dev/null
# fi

cp scripts/* .git/hooks
.git/hooks/post-checkout
