#!/bin/sh
rm "vvvv45/addonpack/lib/nodes/plugins/BézierSpline (Value) help.v4p"
rm "vvvv45/addonpack/lib/nodes/plugins/BézierSpread (Spreads) help.v4p"
rm "vvvv45/addonpack/lib/nodes/plugins/RösslerAttractor (Animation) help.v4p"
rm "vvvv45/lib/nodes/native/BézierLine (GDI) help.v4p"
rm "vvvv45/lib/nodes/native/BézierLoop (GDI) help.v4p"
rm "vvvv45/lib/nodes/native/BézierSpread (Spreads) help.v4p"
