//Builder.h - VSTGUI editor file, automatically generated by VSTGUI Builder

#ifndef Builder_H_
#define Builder_H_

#include "vstgui.h"

class Builder : public AEffGUIEditor, public CControlListener
{
  public:
    Builder(AudioEffect *effect);
    ~Builder();

  protected:
    long open(void *ptr);
    void close();

    long controlModifierClicked(CDrawContext *pContext, CControl *pControl, long button) {return 0;};

    void setParameter(long index, float value);
    void valueChanged(CDrawContext* context, CControl* control);
    void idle();

    //Controls
    COnOffButton *Signal;
    COnOffButton *Adjust;
    COnOffButton *Reset;

    //Bitmaps
    CBitmap *hBack;
    CBitmap *hbutton00;
};

#endif
			