//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18033
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCopyright("Copyright © vvvv group. All rights reserved.")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyCompany("vvvv group")]
[assembly: System.Reflection.AssemblyDescription("The VVVV Utility Library")]
[assembly: System.Reflection.AssemblyProduct("vvvv")]
[assembly: System.Reflection.AssemblyTitle("VVVV.Utils")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("29.5")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCopyright = "Copyright © vvvv group. All rights reserved.";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyCompany = "vvvv group";
    
    internal const string AssemblyDescription = "The VVVV Utility Library";
    
    internal const string AssemblyProduct = "vvvv";
    
    internal const string AssemblyTitle = "VVVV.Utils";
    
    internal const string AssemblyVersion = "1.0.0.0";
    
    internal const string AssemblyFileVersion = "1.0.0.0";
    
    internal const string AssemblyInformationalVersion = "29.5";
    
    private ThisAssembly() {
    }
}
