//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCopyright("Copyright © vvvv group 2013. All rights reserved.")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyCompany("vvvv group")]
[assembly: System.Reflection.AssemblyProduct("vvvv")]
[assembly: System.Reflection.AssemblyTitle("VVVV.Utils")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0.0")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCopyright = "Copyright © vvvv group 2013. All rights reserved.";
    
    internal const string AssemblyConfiguration = "Debug";
    
    internal const string AssemblyCompany = "vvvv group";
    
    internal const string AssemblyProduct = "vvvv";
    
    internal const string AssemblyTitle = "VVVV.Utils";
    
    internal const string AssemblyVersion = "1.0.0.0";
    
    internal const string AssemblyFileVersion = "1.0.0.0";
    
    internal const string AssemblyInformationalVersion = "1.0.0.0";
    
    private ThisAssembly() {
    }
}
