#!/bin/sh

# Archives binaries for fetch-binaries script
binariesArchiveFilename="binaries"

function usage
{
  echo "Usage: archive-binaries [--platform=x86|x64] FILES ..."
}

platform="x86"

while [ -n "$1" ]; do
    case $1 in
        -h | --help )           usage
                                exit
                                ;;
		-p | --platform )		shift
								platform=$1
								;;
        * )                     break
    esac
    shift
done

binaries=$*

echo "Using platform ${platform}."

if [ ! -n "$binaries" ]; then
  echo "No binaries given to archive."
  exit 1
fi

commitId=`git log -1 | grep git-subtree-split | sed -e 's/.* //g'`

# Only archive if last commit was a split
if [ ! -n "$commitId" ]; then
  echo "Last commit is not a git-subtree-split commit. Abort."
  exit
fi

binariesArchiveFile="${binariesArchiveFilename}-${commitId}-${platform}.tar.bz2"
binariesMD5File="${binariesArchiveFilename}-${commitId}-${platform}.tar.bz2.md5"

echo "Creating archive $binariesArchiveFile ..."
tar -jcvf "$binariesArchiveFile" $binaries
echo "Generating checksum for $binariesArchiveFile ..."
md5sum "$binariesArchiveFile" > "$binariesMD5File"
